language: objective-c
osx_image: xcode7.3

cache:
  bundler: true

bundler_args: --jobs 3 --retry 3

rvm:
  - 2.2.1
  - 2.3.1

before_install:
  - gem update --system --no-document
  - gem install bundler -v 1.17.3 --no-document

script: bundle exec rake
